plugins {
    id 'com.android.application'
}

android {
    namespace 'com.auronq.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.auronq.mobile'
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName '0.5.3-three-netgroup-test'
        manifestPlaceholders = [appLabel:'AuronQ Mobile']
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        quick2stage {
            initWith debug
            applicationIdSuffix '.quick2stage'
            versionNameSuffix '-two-stage-test'
            signingConfig signingConfigs.debug
            manifestPlaceholders = [appLabel:'AuronQ Mobile 2-Stage TEST']
        }
        quick3test {
            initWith debug
            applicationIdSuffix '.quick3test'
            versionNameSuffix '-isolated'
            signingConfig signingConfigs.debug
            manifestPlaceholders = [appLabel:'AuronQ Mobile 3-Peer TEST']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation files('libs/auronqmobile.aar')
}
